export const LOAD_USER = 'LOAD_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const USER_PASSWORD_AUTH = 'USER_PASSWORD_AUTH';
export const USER_PASSWORD_AUTH_FAIL = 'USER_PASSWORD_AUTH_FAIL';
export const LOAD_AUTH_USER = 'LOAD_AUTH_USER';
export const LOAD_AUTH_USER_FAIL = 'LOAD_AUTH_USER_FAIL';
export const LOAD_AUTH_USER_POLICY = 'LOAD_AUTH_USER_POLICY';
